# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ff < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/ff-cli/releases/download/v1.0.1/ff_1.0.1_darwin_amd64.tar.gz"
      sha256 "873483e5ea3b2ea523e43c7a77d796f8645eef26f3b632d37c524a06449ad055"

      define_method(:install) do
        bin.install "ff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/ff-cli/releases/download/v1.0.1/ff_1.0.1_darwin_arm64.tar.gz"
      sha256 "b1dbb6b17fe70454ec1567d72c91cc7a379ff0b7bc2361fa603de1cacef1ffa0"

      define_method(:install) do
        bin.install "ff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/ff-cli/releases/download/v1.0.1/ff_1.0.1_linux_amd64.tar.gz"
      sha256 "29517ed6beadd90ded278dffc1be28d66760cecd3087f6cec40d5dc7b90f7a4d"
      define_method(:install) do
        bin.install "ff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/ff-cli/releases/download/v1.0.1/ff_1.0.1_linux_arm64.tar.gz"
      sha256 "a3e9d7d6edd2c1db178fb29c5a5163640a5c5c7b0f86c552548bd2a120b1b6be"
      define_method(:install) do
        bin.install "ff"
      end
    end
  end
end
