# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffly < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/fly/releases/download/v1.2.0/ffly_1.2.0_darwin_amd64.tar.gz"
      sha256 "d210e46734140136f1cda66d727fae9fdedcab1b85a1c4772b01578413f48ff0"

      define_method(:install) do
        bin.install "ffly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/fly/releases/download/v1.2.0/ffly_1.2.0_darwin_arm64.tar.gz"
      sha256 "576918025bd7b819e899ab4f2d5b9f8be2cbaaaa33c1fc7e90a1ad5490541b23"

      define_method(:install) do
        bin.install "ffly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.2.0/ffly_1.2.0_linux_amd64.tar.gz"
      sha256 "1a56a4da5b854c9cc935c2e5714a1b690f6e8c2fc253e4c378fdc08ce40fef44"
      define_method(:install) do
        bin.install "ffly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.2.0/ffly_1.2.0_linux_arm64.tar.gz"
      sha256 "7f8d6a08b89217de43d844f825b615ebf969d4fcfff1f1107459bff25d91cb54"
      define_method(:install) do
        bin.install "ffly"
      end
    end
  end
end
