# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffly < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/ffly_1.1.0_darwin_amd64.tar.gz"
      sha256 "4c7b721febd0ee7f190bc683ccebb5e6c66d12ea115c9824b1228d6b0caee15b"

      define_method(:install) do
        bin.install "ffly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/ffly_1.1.0_darwin_arm64.tar.gz"
      sha256 "0a856f7356dad68f427ae369559b3063763b1cede5ea5416465104d4aa0cac25"

      define_method(:install) do
        bin.install "ffly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/ffly_1.1.0_linux_amd64.tar.gz"
      sha256 "79fbd8af6872acabc59ffbf298e833d8c0ab1831592d592d4f0a5e2b32858750"
      define_method(:install) do
        bin.install "ffly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/ffly_1.1.0_linux_arm64.tar.gz"
      sha256 "3ce80fe039d5611e5ca3bcf9f7bfa23f8f22e7adf079402f1aa75a85f12a7d66"
      define_method(:install) do
        bin.install "ffly"
      end
    end
  end
end
