# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fly < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/fly/releases/download/v1.2.3/fly_1.2.3_darwin_amd64.tar.gz"
      sha256 "763a3cfaa80dcfef98ea5bb1c1741afac2d8f75885b970ee86d433c8026c7f40"

      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/fly/releases/download/v1.2.3/fly_1.2.3_darwin_arm64.tar.gz"
      sha256 "1555c144c022a459c8951b220858e1fc93e38ec15242ecc165e1af9c35d8ecaa"

      define_method(:install) do
        bin.install "fly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.2.3/fly_1.2.3_linux_amd64.tar.gz"
      sha256 "482c3483b7d0c76564342a0a665a6f50c3393bf7c928ee97f156bf4d86d318a9"
      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.2.3/fly_1.2.3_linux_arm64.tar.gz"
      sha256 "2b02dce8b6d087bbd7ceb4c6f99fc0791cd02d58b7c7eeabb3069338da5394af"
      define_method(:install) do
        bin.install "fly"
      end
    end
  end
end
