# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fly < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/fly_1.1.0_darwin_amd64.tar.gz"
      sha256 "37c76b18df26d462209f5cf7bd2f9b309b6518fd90e6f3dc85617cd870e1e7b2"

      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/fly_1.1.0_darwin_arm64.tar.gz"
      sha256 "3e3d32a3526b14bcd928daf049255ff02fac0304cfa3d60aa0450530af39c060"

      define_method(:install) do
        bin.install "fly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/fly_1.1.0_linux_amd64.tar.gz"
      sha256 "6204641a94e9dd6579f0916f9c13f037d555f5247323edda34e7ccad6c307ece"
      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.1.0/fly_1.1.0_linux_arm64.tar.gz"
      sha256 "e33edd0e6bcf8e7b266d82a88a210e919665fadcae6470cf173922560b790bec"
      define_method(:install) do
        bin.install "fly"
      end
    end
  end
end
