# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fly < Formula
  desc "FunctionFly CLI — Go from idea to global API in under 60 seconds"
  homepage "https://functionfly.com"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/functionfly/fly/releases/download/v1.0.0/fly_1.0.0_darwin_amd64.tar.gz"
      sha256 "1faa741e5790a3dac2251145b5b9ea86db0c55622c101b80447f7be5716eefb1"

      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/functionfly/fly/releases/download/v1.0.0/fly_1.0.0_darwin_arm64.tar.gz"
      sha256 "e8177fc462bb0431cf1f256c059ef36a1a5e9452c3ae220b8e3a7f421654711c"

      define_method(:install) do
        bin.install "fly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.0.0/fly_1.0.0_linux_amd64.tar.gz"
      sha256 "bb8a788c5fef0789b189b6018698edfc3dc989b3bf837fb78793f37868574ea8"
      define_method(:install) do
        bin.install "fly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/functionfly/fly/releases/download/v1.0.0/fly_1.0.0_linux_arm64.tar.gz"
      sha256 "a7971165d38a62ed73d85724c11bc7240c2d92de10da5c4518cbebaf21c18f07"
      define_method(:install) do
        bin.install "fly"
      end
    end
  end
end
